#!/bin/bash
# Custom configuration for non-login shells.

# Use these to avoid duplicate path entries.
path_prepend() {
	if [[ ! -d "$1" ]]; then
		return
	elif [[ ! "$PATH" =~ (^|:)"$1"(:|$) ]]; then
		export PATH=$1:$PATH
	fi
}

path_append() {
	if [[ ! -d "$1" ]]; then
		return
	elif [[ ! "$PATH" =~ (^|:)"$1"(:|$) ]]; then
		export PATH=$PATH:$1
	fi
}

set -o vi
shopt -s globstar
HISTSIZE=10000
HISTFILESIZE=1000000

# Disable XON/XOFF flow control.
stty -ixon

# Docker
alias dcln='docker rmi $(docker images -qf dangling=true)'
alias drmc='docker rm $(docker ps -a -q) && dcln'
alias dc='docker compose'
alias docker-compose='docker compose'

# TeX Live
path_append "/usr/local/texlive/2022/bin/x86_64-linux"

# liquidprompt
# shellcheck source-path=SCRIPTDIR/..
[[ $- = *i* ]] && source "$HOME/extern/liquidprompt/liquidprompt"

# fzf: https://github.com/junegunn/fzf
# shellcheck source-path=SCRIPTDIR/..
[ -f ~/.fzf.bash ] && source "$HOME/.fzf.bash"
export FZF_DEFAULT_COMMAND='fd --hidden --type f --type d --strip-cwd-prefix'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# direnv
eval "$(direnv hook bash)"

# mise
# Used for: go, node, python, rust, zig
eval "$(~/.local/bin/mise activate bash)"
