#!/bin/bash
# vim: ft=sh

# Use this to avoid duplicate entries.
path_append() {
	if [[ ! "$PATH" =~ (^|:)"$1"(:|$) ]]; then
		export PATH=$PATH:$1
	fi
}

set -o vi
shopt -s globstar
HISTSIZE=10000
HISTFILESIZE=1000000

# Docker
alias dcln='docker rmi $(docker images -qf dangling=true)'
alias drmc='docker rm $(docker ps -a -q) && dcln'
alias dc='docker-compose'

# Python virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/p
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
. "$HOME"/.local/bin/virtualenvwrapper.sh

# Python pyenv
export PYENV_ROOT=$HOME/.pyenv
path_append "$PYENV_ROOT/bin"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Go
export GO111MODULE=on
export GOPATH=$HOME/go
path_append "/usr/local/go/bin"
path_append "$GOPATH/bin"
alias godir='cd $HOME/go/src/github.com/team-telnyx'

# Rust
path_append "$HOME/.cargo/bin"

# Elixir
path_append "$HOME/e/elixir/bin"

# Node and Yarn
# (Need to create the symlink to this path.)
path_append "$HOME/.yarn/bin"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# liquidprompt
[[ $- = *i* ]] && . ~/extern/liquidprompt/liquidprompt
